### ISSUE TITLE
require menatwork/contao-multicolumnwizard-bundle

### ISSUE THREAD

**Issue by k-webdesign** [terminal42/contao-leads#106] opened 2021-02-03 19:16 UTC
Hey,

Leads still requires "menatwork/contao-multicolumnwizard": "~3.2" which is outdated. Could you switch to menatwork/contao-multicolumnwizard-bundle? I'm experiencing lots of problems due to this when using other extensions which use the MCW.

**Comment by fritzmg** [comment] 2021-02-03 21:07
Duplicate of https://github.com/terminal42/contao-leads/issues/105

> I'm experiencing lots of problems due to this when using other extensions which use the MCW.

If another extension is requiring `menatwork/contao-multicolumnwizard-bundle` then `menatwork/contao-multicolumnwizard` will automatically be replaced with `menatwork/contao-multicolumnwizard-bundle`. However, you need to make sure that you either make a full package update for this to happen.

**Closed** 2023-04-04 19:07 UTC
